/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Account: () => import('#controllers/account_controller'),
  AccountHistory: () => import('#controllers/account_history_controller'),
  admin: {
    ContactMessages: () => import('#controllers/admin/contact_messages_controller'),
    ContentPages: () => import('#controllers/admin/content_pages_controller'),
    Games: () => import('#controllers/admin/games_controller'),
    MediaAssets: () => import('#controllers/admin/media_assets_controller'),
    Panel: () => import('#controllers/admin/panel_controller'),
    QuestionCategories: () => import('#controllers/admin/question_categories_controller'),
    Questions: () => import('#controllers/admin/questions_controller'),
    Reports: () => import('#controllers/admin/reports_controller'),
  },
  Auth: () => import('#controllers/auth_controller'),
  ContactMessages: () => import('#controllers/contact_messages_controller'),
  ContentPages: () => import('#controllers/content_pages_controller'),
  GameSessionPayments: () => import('#controllers/game_session_payments_controller'),
  GameSessions: () => import('#controllers/game_sessions_controller'),
  Gameplay: () => import('#controllers/gameplay_controller'),
  MasterGames: () => import('#controllers/master_games_controller'),
  MediaAssets: () => import('#controllers/media_assets_controller'),
  Payments: () => import('#controllers/payments_controller'),
  RoundQuestions: () => import('#controllers/round_questions_controller'),
  Wallet: () => import('#controllers/wallet_controller'),
}
