/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type AccountHistoryTransformer from '#transformers/account_history_transformer'
import type AdminCmsTransformer from '#transformers/admin_cms_transformer'
import type ContentPageTransformer from '#transformers/content_page_transformer'
import type GameSessionTransformer from '#transformers/game_session_transformer'
import type MasterTransformer from '#transformers/master_transformer'
import type MediaAssetTransformer from '#transformers/media_asset_transformer'
import type PaymentTransformer from '#transformers/payment_transformer'
import type QuestionTransformer from '#transformers/question_transformer'
import type ScoreboardTransformer from '#transformers/scoreboard_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type WalletTransformer from '#transformers/wallet_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type AccountHistory = InferData<AccountHistoryTransformer>
  export namespace AccountHistory {
    export type Variants = InferVariants<AccountHistoryTransformer>
  }
  export type AdminCms = InferData<AdminCmsTransformer>
  export namespace AdminCms {
    export type Variants = InferVariants<AdminCmsTransformer>
  }
  export type ContentPage = InferData<ContentPageTransformer>
  export namespace ContentPage {
    export type Variants = InferVariants<ContentPageTransformer>
  }
  export type GameSession = InferData<GameSessionTransformer>
  export namespace GameSession {
    export type Variants = InferVariants<GameSessionTransformer>
  }
  export type Master = InferData<MasterTransformer>
  export namespace Master {
    export type Variants = InferVariants<MasterTransformer>
  }
  export type MediaAsset = InferData<MediaAssetTransformer>
  export namespace MediaAsset {
    export type Variants = InferVariants<MediaAssetTransformer>
  }
  export type Payment = InferData<PaymentTransformer>
  export namespace Payment {
    export type Variants = InferVariants<PaymentTransformer>
  }
  export type Question = InferData<QuestionTransformer>
  export namespace Question {
    export type Variants = InferVariants<QuestionTransformer>
  }
  export type Scoreboard = InferData<ScoreboardTransformer>
  export namespace Scoreboard {
    export type Variants = InferVariants<ScoreboardTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Wallet = InferData<WalletTransformer>
  export namespace Wallet {
    export type Variants = InferVariants<WalletTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
