/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['home']['types'],
  },
  'auth.web_login_page': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.web_login_page']['types'],
  },
  'auth.web_login': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.web_login']['types'],
  },
  'auth.web_logout': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.web_logout']['types'],
  },
  'admin_panel.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/admin',
    tokens: [{"old":"/admin","type":0,"val":"admin","end":""}],
    types: placeholder as Registry['admin_panel.dashboard']['types'],
  },
  'admin_panel.reports': {
    methods: ["GET","HEAD"],
    pattern: '/admin/reports',
    tokens: [{"old":"/admin/reports","type":0,"val":"admin","end":""},{"old":"/admin/reports","type":0,"val":"reports","end":""}],
    types: placeholder as Registry['admin_panel.reports']['types'],
  },
  'admin_panel.finance': {
    methods: ["GET","HEAD"],
    pattern: '/admin/finance',
    tokens: [{"old":"/admin/finance","type":0,"val":"admin","end":""},{"old":"/admin/finance","type":0,"val":"finance","end":""}],
    types: placeholder as Registry['admin_panel.finance']['types'],
  },
  'admin_panel.profile': {
    methods: ["GET","HEAD"],
    pattern: '/admin/profile',
    tokens: [{"old":"/admin/profile","type":0,"val":"admin","end":""},{"old":"/admin/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['admin_panel.profile']['types'],
  },
  'admin_panel.profile_update_password': {
    methods: ["PATCH"],
    pattern: '/admin/profile/password',
    tokens: [{"old":"/admin/profile/password","type":0,"val":"admin","end":""},{"old":"/admin/profile/password","type":0,"val":"profile","end":""},{"old":"/admin/profile/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['admin_panel.profile_update_password']['types'],
  },
  'admin_panel.users': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin_panel.users']['types'],
  },
  'admin_panel.user_show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_panel.user_show']['types'],
  },
  'admin_panel.games': {
    methods: ["GET","HEAD"],
    pattern: '/admin/games',
    tokens: [{"old":"/admin/games","type":0,"val":"admin","end":""},{"old":"/admin/games","type":0,"val":"games","end":""}],
    types: placeholder as Registry['admin_panel.games']['types'],
  },
  'admin_panel.game_create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/games/create',
    tokens: [{"old":"/admin/games/create","type":0,"val":"admin","end":""},{"old":"/admin/games/create","type":0,"val":"games","end":""},{"old":"/admin/games/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin_panel.game_create']['types'],
  },
  'admin_panel.game_store': {
    methods: ["POST"],
    pattern: '/admin/games',
    tokens: [{"old":"/admin/games","type":0,"val":"admin","end":""},{"old":"/admin/games","type":0,"val":"games","end":""}],
    types: placeholder as Registry['admin_panel.game_store']['types'],
  },
  'admin_panel.game_edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/games/:id/edit',
    tokens: [{"old":"/admin/games/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/games/:id/edit","type":0,"val":"games","end":""},{"old":"/admin/games/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/games/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin_panel.game_edit']['types'],
  },
  'admin_panel.game_update': {
    methods: ["PUT"],
    pattern: '/admin/games/:id',
    tokens: [{"old":"/admin/games/:id","type":0,"val":"admin","end":""},{"old":"/admin/games/:id","type":0,"val":"games","end":""},{"old":"/admin/games/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_panel.game_update']['types'],
  },
  'admin_panel.game_update_status': {
    methods: ["PATCH"],
    pattern: '/admin/games/:id/status',
    tokens: [{"old":"/admin/games/:id/status","type":0,"val":"admin","end":""},{"old":"/admin/games/:id/status","type":0,"val":"games","end":""},{"old":"/admin/games/:id/status","type":1,"val":"id","end":""},{"old":"/admin/games/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin_panel.game_update_status']['types'],
  },
  'admin_panel.game_show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/games/:id',
    tokens: [{"old":"/admin/games/:id","type":0,"val":"admin","end":""},{"old":"/admin/games/:id","type":0,"val":"games","end":""},{"old":"/admin/games/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_panel.game_show']['types'],
  },
  'admin_panel.categories': {
    methods: ["GET","HEAD"],
    pattern: '/admin/categories',
    tokens: [{"old":"/admin/categories","type":0,"val":"admin","end":""},{"old":"/admin/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin_panel.categories']['types'],
  },
  'admin_panel.category_create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/categories/create',
    tokens: [{"old":"/admin/categories/create","type":0,"val":"admin","end":""},{"old":"/admin/categories/create","type":0,"val":"categories","end":""},{"old":"/admin/categories/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin_panel.category_create']['types'],
  },
  'admin_panel.category_store': {
    methods: ["POST"],
    pattern: '/admin/categories',
    tokens: [{"old":"/admin/categories","type":0,"val":"admin","end":""},{"old":"/admin/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin_panel.category_store']['types'],
  },
  'admin_panel.category_edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/categories/:id/edit',
    tokens: [{"old":"/admin/categories/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/categories/:id/edit","type":0,"val":"categories","end":""},{"old":"/admin/categories/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/categories/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin_panel.category_edit']['types'],
  },
  'admin_panel.category_update': {
    methods: ["PUT"],
    pattern: '/admin/categories/:id',
    tokens: [{"old":"/admin/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_panel.category_update']['types'],
  },
  'admin_panel.category_update_status': {
    methods: ["PATCH"],
    pattern: '/admin/categories/:id/status',
    tokens: [{"old":"/admin/categories/:id/status","type":0,"val":"admin","end":""},{"old":"/admin/categories/:id/status","type":0,"val":"categories","end":""},{"old":"/admin/categories/:id/status","type":1,"val":"id","end":""},{"old":"/admin/categories/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin_panel.category_update_status']['types'],
  },
  'admin_panel.category_show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/categories/:id',
    tokens: [{"old":"/admin/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_panel.category_show']['types'],
  },
  'admin_panel.questions': {
    methods: ["GET","HEAD"],
    pattern: '/admin/questions',
    tokens: [{"old":"/admin/questions","type":0,"val":"admin","end":""},{"old":"/admin/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['admin_panel.questions']['types'],
  },
  'admin_panel.question_create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/questions/create',
    tokens: [{"old":"/admin/questions/create","type":0,"val":"admin","end":""},{"old":"/admin/questions/create","type":0,"val":"questions","end":""},{"old":"/admin/questions/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin_panel.question_create']['types'],
  },
  'admin_panel.question_store': {
    methods: ["POST"],
    pattern: '/admin/questions',
    tokens: [{"old":"/admin/questions","type":0,"val":"admin","end":""},{"old":"/admin/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['admin_panel.question_store']['types'],
  },
  'admin_panel.question_edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/questions/:id/edit',
    tokens: [{"old":"/admin/questions/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/questions/:id/edit","type":0,"val":"questions","end":""},{"old":"/admin/questions/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/questions/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin_panel.question_edit']['types'],
  },
  'admin_panel.question_update': {
    methods: ["PUT"],
    pattern: '/admin/questions/:id',
    tokens: [{"old":"/admin/questions/:id","type":0,"val":"admin","end":""},{"old":"/admin/questions/:id","type":0,"val":"questions","end":""},{"old":"/admin/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_panel.question_update']['types'],
  },
  'admin_panel.question_update_status': {
    methods: ["PATCH"],
    pattern: '/admin/questions/:id/status',
    tokens: [{"old":"/admin/questions/:id/status","type":0,"val":"admin","end":""},{"old":"/admin/questions/:id/status","type":0,"val":"questions","end":""},{"old":"/admin/questions/:id/status","type":1,"val":"id","end":""},{"old":"/admin/questions/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin_panel.question_update_status']['types'],
  },
  'admin_panel.question_show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/questions/:id',
    tokens: [{"old":"/admin/questions/:id","type":0,"val":"admin","end":""},{"old":"/admin/questions/:id","type":0,"val":"questions","end":""},{"old":"/admin/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_panel.question_show']['types'],
  },
  'admin_panel.media_assets': {
    methods: ["GET","HEAD"],
    pattern: '/admin/media-assets',
    tokens: [{"old":"/admin/media-assets","type":0,"val":"admin","end":""},{"old":"/admin/media-assets","type":0,"val":"media-assets","end":""}],
    types: placeholder as Registry['admin_panel.media_assets']['types'],
  },
  'admin_panel_media_assets.store': {
    methods: ["POST"],
    pattern: '/admin/media-assets',
    tokens: [{"old":"/admin/media-assets","type":0,"val":"admin","end":""},{"old":"/admin/media-assets","type":0,"val":"media-assets","end":""}],
    types: placeholder as Registry['admin_panel_media_assets.store']['types'],
  },
  'admin_panel.content_pages': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content-pages',
    tokens: [{"old":"/admin/content-pages","type":0,"val":"admin","end":""},{"old":"/admin/content-pages","type":0,"val":"content-pages","end":""}],
    types: placeholder as Registry['admin_panel.content_pages']['types'],
  },
  'admin_panel.content_page_create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content-pages/create',
    tokens: [{"old":"/admin/content-pages/create","type":0,"val":"admin","end":""},{"old":"/admin/content-pages/create","type":0,"val":"content-pages","end":""},{"old":"/admin/content-pages/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin_panel.content_page_create']['types'],
  },
  'admin_panel.content_page_store': {
    methods: ["POST"],
    pattern: '/admin/content-pages',
    tokens: [{"old":"/admin/content-pages","type":0,"val":"admin","end":""},{"old":"/admin/content-pages","type":0,"val":"content-pages","end":""}],
    types: placeholder as Registry['admin_panel.content_page_store']['types'],
  },
  'admin_panel.content_page_edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content-pages/:id/edit',
    tokens: [{"old":"/admin/content-pages/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/content-pages/:id/edit","type":0,"val":"content-pages","end":""},{"old":"/admin/content-pages/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/content-pages/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin_panel.content_page_edit']['types'],
  },
  'admin_panel.content_page_update': {
    methods: ["PUT"],
    pattern: '/admin/content-pages/:id',
    tokens: [{"old":"/admin/content-pages/:id","type":0,"val":"admin","end":""},{"old":"/admin/content-pages/:id","type":0,"val":"content-pages","end":""},{"old":"/admin/content-pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_panel.content_page_update']['types'],
  },
  'admin_panel.content_page_update_status': {
    methods: ["PATCH"],
    pattern: '/admin/content-pages/:id/status',
    tokens: [{"old":"/admin/content-pages/:id/status","type":0,"val":"admin","end":""},{"old":"/admin/content-pages/:id/status","type":0,"val":"content-pages","end":""},{"old":"/admin/content-pages/:id/status","type":1,"val":"id","end":""},{"old":"/admin/content-pages/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin_panel.content_page_update_status']['types'],
  },
  'admin_panel.contact_messages': {
    methods: ["GET","HEAD"],
    pattern: '/admin/contact-messages',
    tokens: [{"old":"/admin/contact-messages","type":0,"val":"admin","end":""},{"old":"/admin/contact-messages","type":0,"val":"contact-messages","end":""}],
    types: placeholder as Registry['admin_panel.contact_messages']['types'],
  },
  'admin_panel.contact_message_show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/contact-messages/:id',
    tokens: [{"old":"/admin/contact-messages/:id","type":0,"val":"admin","end":""},{"old":"/admin/contact-messages/:id","type":0,"val":"contact-messages","end":""},{"old":"/admin/contact-messages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_panel.contact_message_show']['types'],
  },
  'admin_panel.user_update_status': {
    methods: ["PATCH"],
    pattern: '/admin/users/:id/status',
    tokens: [{"old":"/admin/users/:id/status","type":0,"val":"admin","end":""},{"old":"/admin/users/:id/status","type":0,"val":"users","end":""},{"old":"/admin/users/:id/status","type":1,"val":"id","end":""},{"old":"/admin/users/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin_panel.user_update_status']['types'],
  },
  'admin_panel.contact_message_update_status': {
    methods: ["PATCH"],
    pattern: '/admin/contact-messages/:id/status',
    tokens: [{"old":"/admin/contact-messages/:id/status","type":0,"val":"admin","end":""},{"old":"/admin/contact-messages/:id/status","type":0,"val":"contact-messages","end":""},{"old":"/admin/contact-messages/:id/status","type":1,"val":"id","end":""},{"old":"/admin/contact-messages/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin_panel.contact_message_update_status']['types'],
  },
  'auth.register': {
    methods: ["POST"],
    pattern: '/api/v1/auth/register',
    tokens: [{"old":"/api/v1/auth/register","type":0,"val":"api","end":""},{"old":"/api/v1/auth/register","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/register","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/me',
    tokens: [{"old":"/api/v1/auth/me","type":0,"val":"api","end":""},{"old":"/api/v1/auth/me","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/me","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me']['types'],
  },
  'auth.logout': {
    methods: ["POST"],
    pattern: '/api/v1/auth/logout',
    tokens: [{"old":"/api/v1/auth/logout","type":0,"val":"api","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'auth.send_phone_otp': {
    methods: ["POST"],
    pattern: '/api/v1/auth/otp/phone/send',
    tokens: [{"old":"/api/v1/auth/otp/phone/send","type":0,"val":"api","end":""},{"old":"/api/v1/auth/otp/phone/send","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/otp/phone/send","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/otp/phone/send","type":0,"val":"otp","end":""},{"old":"/api/v1/auth/otp/phone/send","type":0,"val":"phone","end":""},{"old":"/api/v1/auth/otp/phone/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['auth.send_phone_otp']['types'],
  },
  'auth.verify_phone_otp': {
    methods: ["POST"],
    pattern: '/api/v1/auth/otp/phone/verify',
    tokens: [{"old":"/api/v1/auth/otp/phone/verify","type":0,"val":"api","end":""},{"old":"/api/v1/auth/otp/phone/verify","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/otp/phone/verify","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/otp/phone/verify","type":0,"val":"otp","end":""},{"old":"/api/v1/auth/otp/phone/verify","type":0,"val":"phone","end":""},{"old":"/api/v1/auth/otp/phone/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['auth.verify_phone_otp']['types'],
  },
  'account.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/me',
    tokens: [{"old":"/api/v1/account/me","type":0,"val":"api","end":""},{"old":"/api/v1/account/me","type":0,"val":"v1","end":""},{"old":"/api/v1/account/me","type":0,"val":"account","end":""},{"old":"/api/v1/account/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['account.me']['types'],
  },
  'account.update_profile': {
    methods: ["PATCH"],
    pattern: '/api/v1/account/profile',
    tokens: [{"old":"/api/v1/account/profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['account.update_profile']['types'],
  },
  'account.change_password': {
    methods: ["PATCH"],
    pattern: '/api/v1/account/password',
    tokens: [{"old":"/api/v1/account/password","type":0,"val":"api","end":""},{"old":"/api/v1/account/password","type":0,"val":"v1","end":""},{"old":"/api/v1/account/password","type":0,"val":"account","end":""},{"old":"/api/v1/account/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['account.change_password']['types'],
  },
  'account_history.game_history': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/game-history',
    tokens: [{"old":"/api/v1/account/game-history","type":0,"val":"api","end":""},{"old":"/api/v1/account/game-history","type":0,"val":"v1","end":""},{"old":"/api/v1/account/game-history","type":0,"val":"account","end":""},{"old":"/api/v1/account/game-history","type":0,"val":"game-history","end":""}],
    types: placeholder as Registry['account_history.game_history']['types'],
  },
  'account_history.game_history_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/game-history/:id',
    tokens: [{"old":"/api/v1/account/game-history/:id","type":0,"val":"api","end":""},{"old":"/api/v1/account/game-history/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/account/game-history/:id","type":0,"val":"account","end":""},{"old":"/api/v1/account/game-history/:id","type":0,"val":"game-history","end":""},{"old":"/api/v1/account/game-history/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['account_history.game_history_show']['types'],
  },
  'account_history.purchased_history': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/purchased-history',
    tokens: [{"old":"/api/v1/account/purchased-history","type":0,"val":"api","end":""},{"old":"/api/v1/account/purchased-history","type":0,"val":"v1","end":""},{"old":"/api/v1/account/purchased-history","type":0,"val":"account","end":""},{"old":"/api/v1/account/purchased-history","type":0,"val":"purchased-history","end":""}],
    types: placeholder as Registry['account_history.purchased_history']['types'],
  },
  'account_history.credit_transactions': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/credit-transactions',
    tokens: [{"old":"/api/v1/account/credit-transactions","type":0,"val":"api","end":""},{"old":"/api/v1/account/credit-transactions","type":0,"val":"v1","end":""},{"old":"/api/v1/account/credit-transactions","type":0,"val":"account","end":""},{"old":"/api/v1/account/credit-transactions","type":0,"val":"credit-transactions","end":""}],
    types: placeholder as Registry['account_history.credit_transactions']['types'],
  },
  'content_pages.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/pages/:slug',
    tokens: [{"old":"/api/v1/pages/:slug","type":0,"val":"api","end":""},{"old":"/api/v1/pages/:slug","type":0,"val":"v1","end":""},{"old":"/api/v1/pages/:slug","type":0,"val":"pages","end":""},{"old":"/api/v1/pages/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['content_pages.show']['types'],
  },
  'contact_messages.store': {
    methods: ["POST"],
    pattern: '/api/v1/contact',
    tokens: [{"old":"/api/v1/contact","type":0,"val":"api","end":""},{"old":"/api/v1/contact","type":0,"val":"v1","end":""},{"old":"/api/v1/contact","type":0,"val":"contact","end":""}],
    types: placeholder as Registry['contact_messages.store']['types'],
  },
  'media_assets.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/media-assets/:id/file',
    tokens: [{"old":"/api/v1/media-assets/:id/file","type":0,"val":"api","end":""},{"old":"/api/v1/media-assets/:id/file","type":0,"val":"v1","end":""},{"old":"/api/v1/media-assets/:id/file","type":0,"val":"media-assets","end":""},{"old":"/api/v1/media-assets/:id/file","type":1,"val":"id","end":""},{"old":"/api/v1/media-assets/:id/file","type":0,"val":"file","end":""}],
    types: placeholder as Registry['media_assets.show']['types'],
  },
  'master_games.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/master/games',
    tokens: [{"old":"/api/v1/master/games","type":0,"val":"api","end":""},{"old":"/api/v1/master/games","type":0,"val":"v1","end":""},{"old":"/api/v1/master/games","type":0,"val":"master","end":""},{"old":"/api/v1/master/games","type":0,"val":"games","end":""}],
    types: placeholder as Registry['master_games.index']['types'],
  },
  'master_games.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/master/games/:slug',
    tokens: [{"old":"/api/v1/master/games/:slug","type":0,"val":"api","end":""},{"old":"/api/v1/master/games/:slug","type":0,"val":"v1","end":""},{"old":"/api/v1/master/games/:slug","type":0,"val":"master","end":""},{"old":"/api/v1/master/games/:slug","type":0,"val":"games","end":""},{"old":"/api/v1/master/games/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['master_games.show']['types'],
  },
  'game_sessions.store': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions',
    tokens: [{"old":"/api/v1/game-sessions","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions","type":0,"val":"game-sessions","end":""}],
    types: placeholder as Registry['game_sessions.store']['types'],
  },
  'game_sessions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/game-sessions/:id/setup',
    tokens: [{"old":"/api/v1/game-sessions/:id/setup","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/setup","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/setup","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/setup","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/setup","type":0,"val":"setup","end":""}],
    types: placeholder as Registry['game_sessions.show']['types'],
  },
  'game_sessions.update_teams': {
    methods: ["PATCH"],
    pattern: '/api/v1/game-sessions/:id/teams',
    tokens: [{"old":"/api/v1/game-sessions/:id/teams","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/teams","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/teams","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/teams","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/teams","type":0,"val":"teams","end":""}],
    types: placeholder as Registry['game_sessions.update_teams']['types'],
  },
  'game_sessions.update_settings': {
    methods: ["PATCH"],
    pattern: '/api/v1/game-sessions/:id/settings',
    tokens: [{"old":"/api/v1/game-sessions/:id/settings","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/settings","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/settings","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/settings","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['game_sessions.update_settings']['types'],
  },
  'game_sessions.select_optional_category': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/optional-category',
    tokens: [{"old":"/api/v1/game-sessions/:id/optional-category","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/optional-category","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/optional-category","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/optional-category","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/optional-category","type":0,"val":"optional-category","end":""}],
    types: placeholder as Registry['game_sessions.select_optional_category']['types'],
  },
  'game_sessions.lock': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/lock',
    tokens: [{"old":"/api/v1/game-sessions/:id/lock","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/lock","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/lock","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/lock","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/lock","type":0,"val":"lock","end":""}],
    types: placeholder as Registry['game_sessions.lock']['types'],
  },
  'game_session_payments.reserve_credits': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/reserve-credits',
    tokens: [{"old":"/api/v1/game-sessions/:id/reserve-credits","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/reserve-credits","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/reserve-credits","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/reserve-credits","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/reserve-credits","type":0,"val":"reserve-credits","end":""}],
    types: placeholder as Registry['game_session_payments.reserve_credits']['types'],
  },
  'game_session_payments.create_category_payment_intent': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/category-payment-intent',
    tokens: [{"old":"/api/v1/game-sessions/:id/category-payment-intent","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/category-payment-intent","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/category-payment-intent","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/category-payment-intent","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/category-payment-intent","type":0,"val":"category-payment-intent","end":""}],
    types: placeholder as Registry['game_session_payments.create_category_payment_intent']['types'],
  },
  'gameplay.start': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/start',
    tokens: [{"old":"/api/v1/game-sessions/:id/start","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/start","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/start","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/start","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['gameplay.start']['types'],
  },
  'gameplay.start_next_round': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/rounds/next',
    tokens: [{"old":"/api/v1/game-sessions/:id/rounds/next","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/rounds/next","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/rounds/next","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/rounds/next","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/rounds/next","type":0,"val":"rounds","end":""},{"old":"/api/v1/game-sessions/:id/rounds/next","type":0,"val":"next","end":""}],
    types: placeholder as Registry['gameplay.start_next_round']['types'],
  },
  'gameplay.complete_round': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/rounds/:roundId/complete',
    tokens: [{"old":"/api/v1/game-sessions/:id/rounds/:roundId/complete","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/complete","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/complete","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/complete","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/complete","type":0,"val":"rounds","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/complete","type":1,"val":"roundId","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/complete","type":0,"val":"complete","end":""}],
    types: placeholder as Registry['gameplay.complete_round']['types'],
  },
  'gameplay.abandon_round': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/rounds/:roundId/abandon',
    tokens: [{"old":"/api/v1/game-sessions/:id/rounds/:roundId/abandon","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/abandon","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/abandon","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/abandon","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/abandon","type":0,"val":"rounds","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/abandon","type":1,"val":"roundId","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/abandon","type":0,"val":"abandon","end":""}],
    types: placeholder as Registry['gameplay.abandon_round']['types'],
  },
  'round_questions.assign_question': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/rounds/:roundId/question',
    tokens: [{"old":"/api/v1/game-sessions/:id/rounds/:roundId/question","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/question","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/question","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/question","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/question","type":0,"val":"rounds","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/question","type":1,"val":"roundId","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/question","type":0,"val":"question","end":""}],
    types: placeholder as Registry['round_questions.assign_question']['types'],
  },
  'round_questions.score': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/rounds/:roundId/score',
    tokens: [{"old":"/api/v1/game-sessions/:id/rounds/:roundId/score","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/score","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/score","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/score","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/score","type":0,"val":"rounds","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/score","type":1,"val":"roundId","end":""},{"old":"/api/v1/game-sessions/:id/rounds/:roundId/score","type":0,"val":"score","end":""}],
    types: placeholder as Registry['round_questions.score']['types'],
  },
  'round_questions.scoreboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/game-sessions/:id/scoreboard',
    tokens: [{"old":"/api/v1/game-sessions/:id/scoreboard","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/scoreboard","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/scoreboard","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/scoreboard","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/scoreboard","type":0,"val":"scoreboard","end":""}],
    types: placeholder as Registry['round_questions.scoreboard']['types'],
  },
  'gameplay.stop': {
    methods: ["POST"],
    pattern: '/api/v1/game-sessions/:id/stop',
    tokens: [{"old":"/api/v1/game-sessions/:id/stop","type":0,"val":"api","end":""},{"old":"/api/v1/game-sessions/:id/stop","type":0,"val":"v1","end":""},{"old":"/api/v1/game-sessions/:id/stop","type":0,"val":"game-sessions","end":""},{"old":"/api/v1/game-sessions/:id/stop","type":1,"val":"id","end":""},{"old":"/api/v1/game-sessions/:id/stop","type":0,"val":"stop","end":""}],
    types: placeholder as Registry['gameplay.stop']['types'],
  },
  'wallet.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/wallet',
    tokens: [{"old":"/api/v1/wallet","type":0,"val":"api","end":""},{"old":"/api/v1/wallet","type":0,"val":"v1","end":""},{"old":"/api/v1/wallet","type":0,"val":"wallet","end":""}],
    types: placeholder as Registry['wallet.show']['types'],
  },
  'payments.confirm': {
    methods: ["POST"],
    pattern: '/api/v1/payments/:id/confirm',
    tokens: [{"old":"/api/v1/payments/:id/confirm","type":0,"val":"api","end":""},{"old":"/api/v1/payments/:id/confirm","type":0,"val":"v1","end":""},{"old":"/api/v1/payments/:id/confirm","type":0,"val":"payments","end":""},{"old":"/api/v1/payments/:id/confirm","type":1,"val":"id","end":""},{"old":"/api/v1/payments/:id/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['payments.confirm']['types'],
  },
  'admin_games.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/games',
    tokens: [{"old":"/api/v1/admin/games","type":0,"val":"api","end":""},{"old":"/api/v1/admin/games","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/games","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/games","type":0,"val":"games","end":""}],
    types: placeholder as Registry['admin_games.index']['types'],
  },
  'admin_games.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/games',
    tokens: [{"old":"/api/v1/admin/games","type":0,"val":"api","end":""},{"old":"/api/v1/admin/games","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/games","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/games","type":0,"val":"games","end":""}],
    types: placeholder as Registry['admin_games.store']['types'],
  },
  'admin_games.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/games/:id',
    tokens: [{"old":"/api/v1/admin/games/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/games/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/games/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/games/:id","type":0,"val":"games","end":""},{"old":"/api/v1/admin/games/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_games.show']['types'],
  },
  'admin_games.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/games/:id',
    tokens: [{"old":"/api/v1/admin/games/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/games/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/games/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/games/:id","type":0,"val":"games","end":""},{"old":"/api/v1/admin/games/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_games.update']['types'],
  },
  'admin_question_categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/games/:gameId/categories',
    tokens: [{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"api","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"games","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":1,"val":"gameId","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin_question_categories.index']['types'],
  },
  'admin_question_categories.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/games/:gameId/categories',
    tokens: [{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"api","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"games","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":1,"val":"gameId","end":""},{"old":"/api/v1/admin/games/:gameId/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin_question_categories.store']['types'],
  },
  'admin_question_categories.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/categories/:id',
    tokens: [{"old":"/api/v1/admin/categories/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/categories/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/categories/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/v1/admin/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_question_categories.show']['types'],
  },
  'admin_question_categories.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/categories/:id',
    tokens: [{"old":"/api/v1/admin/categories/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/categories/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/categories/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/v1/admin/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_question_categories.update']['types'],
  },
  'admin_questions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/questions',
    tokens: [{"old":"/api/v1/admin/questions","type":0,"val":"api","end":""},{"old":"/api/v1/admin/questions","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/questions","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['admin_questions.index']['types'],
  },
  'admin_questions.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/questions',
    tokens: [{"old":"/api/v1/admin/questions","type":0,"val":"api","end":""},{"old":"/api/v1/admin/questions","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/questions","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['admin_questions.store']['types'],
  },
  'admin_questions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/questions/:id',
    tokens: [{"old":"/api/v1/admin/questions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/questions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/questions/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/questions/:id","type":0,"val":"questions","end":""},{"old":"/api/v1/admin/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_questions.show']['types'],
  },
  'admin_questions.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/questions/:id',
    tokens: [{"old":"/api/v1/admin/questions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/questions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/questions/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/questions/:id","type":0,"val":"questions","end":""},{"old":"/api/v1/admin/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_questions.update']['types'],
  },
  'admin_media_assets.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/media-assets',
    tokens: [{"old":"/api/v1/admin/media-assets","type":0,"val":"api","end":""},{"old":"/api/v1/admin/media-assets","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/media-assets","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/media-assets","type":0,"val":"media-assets","end":""}],
    types: placeholder as Registry['admin_media_assets.index']['types'],
  },
  'admin_api_media_assets.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/media-assets',
    tokens: [{"old":"/api/v1/admin/media-assets","type":0,"val":"api","end":""},{"old":"/api/v1/admin/media-assets","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/media-assets","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/media-assets","type":0,"val":"media-assets","end":""}],
    types: placeholder as Registry['admin_api_media_assets.store']['types'],
  },
  'admin_media_assets.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/media-assets/:id',
    tokens: [{"old":"/api/v1/admin/media-assets/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/media-assets/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/media-assets/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/media-assets/:id","type":0,"val":"media-assets","end":""},{"old":"/api/v1/admin/media-assets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_media_assets.show']['types'],
  },
  'admin_content_pages.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/content-pages',
    tokens: [{"old":"/api/v1/admin/content-pages","type":0,"val":"api","end":""},{"old":"/api/v1/admin/content-pages","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/content-pages","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/content-pages","type":0,"val":"content-pages","end":""}],
    types: placeholder as Registry['admin_content_pages.index']['types'],
  },
  'admin_content_pages.store': {
    methods: ["POST"],
    pattern: '/api/v1/admin/content-pages',
    tokens: [{"old":"/api/v1/admin/content-pages","type":0,"val":"api","end":""},{"old":"/api/v1/admin/content-pages","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/content-pages","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/content-pages","type":0,"val":"content-pages","end":""}],
    types: placeholder as Registry['admin_content_pages.store']['types'],
  },
  'admin_content_pages.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/content-pages/:id',
    tokens: [{"old":"/api/v1/admin/content-pages/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/content-pages/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/content-pages/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/content-pages/:id","type":0,"val":"content-pages","end":""},{"old":"/api/v1/admin/content-pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_content_pages.show']['types'],
  },
  'admin_content_pages.update': {
    methods: ["PUT"],
    pattern: '/api/v1/admin/content-pages/:id',
    tokens: [{"old":"/api/v1/admin/content-pages/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/content-pages/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/content-pages/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/content-pages/:id","type":0,"val":"content-pages","end":""},{"old":"/api/v1/admin/content-pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_content_pages.update']['types'],
  },
  'admin_contact_messages.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/contact-messages',
    tokens: [{"old":"/api/v1/admin/contact-messages","type":0,"val":"api","end":""},{"old":"/api/v1/admin/contact-messages","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/contact-messages","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/contact-messages","type":0,"val":"contact-messages","end":""}],
    types: placeholder as Registry['admin_contact_messages.index']['types'],
  },
  'admin_contact_messages.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/contact-messages/:id',
    tokens: [{"old":"/api/v1/admin/contact-messages/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/contact-messages/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/contact-messages/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/contact-messages/:id","type":0,"val":"contact-messages","end":""},{"old":"/api/v1/admin/contact-messages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_contact_messages.show']['types'],
  },
  'admin_contact_messages.update_status': {
    methods: ["PATCH"],
    pattern: '/api/v1/admin/contact-messages/:id/status',
    tokens: [{"old":"/api/v1/admin/contact-messages/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/admin/contact-messages/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/contact-messages/:id/status","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/contact-messages/:id/status","type":0,"val":"contact-messages","end":""},{"old":"/api/v1/admin/contact-messages/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/admin/contact-messages/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin_contact_messages.update_status']['types'],
  },
  'admin_reports.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/dashboard/summary',
    tokens: [{"old":"/api/v1/admin/dashboard/summary","type":0,"val":"api","end":""},{"old":"/api/v1/admin/dashboard/summary","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/dashboard/summary","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/dashboard/summary","type":0,"val":"dashboard","end":""},{"old":"/api/v1/admin/dashboard/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['admin_reports.summary']['types'],
  },
  'admin_reports.payments': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/reports/payments',
    tokens: [{"old":"/api/v1/admin/reports/payments","type":0,"val":"api","end":""},{"old":"/api/v1/admin/reports/payments","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/reports/payments","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/reports/payments","type":0,"val":"reports","end":""},{"old":"/api/v1/admin/reports/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['admin_reports.payments']['types'],
  },
  'admin_reports.game_sessions': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/reports/game-sessions',
    tokens: [{"old":"/api/v1/admin/reports/game-sessions","type":0,"val":"api","end":""},{"old":"/api/v1/admin/reports/game-sessions","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/reports/game-sessions","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/reports/game-sessions","type":0,"val":"reports","end":""},{"old":"/api/v1/admin/reports/game-sessions","type":0,"val":"game-sessions","end":""}],
    types: placeholder as Registry['admin_reports.game_sessions']['types'],
  },
  'admin_reports.users': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/reports/users',
    tokens: [{"old":"/api/v1/admin/reports/users","type":0,"val":"api","end":""},{"old":"/api/v1/admin/reports/users","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/reports/users","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/reports/users","type":0,"val":"reports","end":""},{"old":"/api/v1/admin/reports/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin_reports.users']['types'],
  },
  'admin_reports.contact_messages': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/reports/contact-messages',
    tokens: [{"old":"/api/v1/admin/reports/contact-messages","type":0,"val":"api","end":""},{"old":"/api/v1/admin/reports/contact-messages","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/reports/contact-messages","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/reports/contact-messages","type":0,"val":"reports","end":""},{"old":"/api/v1/admin/reports/contact-messages","type":0,"val":"contact-messages","end":""}],
    types: placeholder as Registry['admin_reports.contact_messages']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
